# Cinemator
version: '3.0'

services:
  db:
    image: postgres:12-alpine
    container_name: cinemator-db
    volumes:
      - cinemator-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: 
      - .env

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  cinemator-db-data: